// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hellosvc.proto
#ifndef GRPC_hellosvc_2eproto__INCLUDED
#define GRPC_hellosvc_2eproto__INCLUDED

#include "hellosvc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class Channel;
class CompletionQueue;
class ServerCompletionQueue;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc_impl

namespace grpc {
class ServerContext;
}  // namespace grpc

namespace hellosvc {

class HelloSvc final {
 public:
  static constexpr char const* service_full_name() {
    return "hellosvc.HelloSvc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status hello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::hellosvc::HelloResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hellosvc::HelloResponse>> Asynchello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hellosvc::HelloResponse>>(AsynchelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hellosvc::HelloResponse>> PrepareAsynchello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hellosvc::HelloResponse>>(PrepareAsynchelloRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void hello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hellosvc::HelloResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void hello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hellosvc::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hellosvc::HelloResponse>* AsynchelloRaw(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hellosvc::HelloResponse>* PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status hello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::hellosvc::HelloResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hellosvc::HelloResponse>> Asynchello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hellosvc::HelloResponse>>(AsynchelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hellosvc::HelloResponse>> PrepareAsynchello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hellosvc::HelloResponse>>(PrepareAsynchelloRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void hello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response, std::function<void(::grpc::Status)>) override;
      void hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hellosvc::HelloResponse* response, std::function<void(::grpc::Status)>) override;
      void hello(::grpc::ClientContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hellosvc::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hellosvc::HelloResponse>* AsynchelloRaw(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hellosvc::HelloResponse>* PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::hellosvc::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_hello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_hello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthello(::grpc::ServerContext* context, ::hellosvc::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::hellosvc::HelloResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_hello<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_hello() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::hellosvc::HelloRequest, ::hellosvc::HelloResponse>(
          [this](::grpc::ServerContext* context,
                 const ::hellosvc::HelloRequest* request,
                 ::hellosvc::HelloResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->hello(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_hello(
        ::grpc::experimental::MessageAllocator< ::hellosvc::HelloRequest, ::hellosvc::HelloResponse>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hellosvc::HelloRequest, ::hellosvc::HelloResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_hello<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_hello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_hello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_hello() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->hello(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void hello(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_hello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::hellosvc::HelloRequest, ::hellosvc::HelloResponse>(std::bind(&WithStreamedUnaryMethod_hello<BaseClass>::Streamedhello, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::hellosvc::HelloRequest* request, ::hellosvc::HelloResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedhello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hellosvc::HelloRequest,::hellosvc::HelloResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_hello<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_hello<Service > StreamedService;
};

}  // namespace hellosvc


#endif  // GRPC_hellosvc_2eproto__INCLUDED
